apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: auth-service
  labels:
    app: auth-service
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: auth-service
  labels:
    app: auth-service
spec:
  source:
    type: Binary
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
      buildArgs:
        - name: JAR_FILE
          value: app.jar
  output:
    to:
      kind: ImageStreamTag
      name: auth-service:latest
  triggers:
    - type: ConfigChange